/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-old-moon-6b8498da3da94e05b832b5e236755708
Title: The Old Moon
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cloud(props) {
  const { nodes, materials } = useGLTF('/models/the_old_moon.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.OldMoon_LP_1_0.geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/the_old_moon.glb')